class AppStrings {
  /// Localized label for a payment method key (see AppConstants.paymentMethods).
  static String methodLabel(String method, String lang) {
    final key = switch (method) {
      'Cash' => 'method_cash',
      'Bankak' => 'method_bankak',
      'Bede' => 'method_bede',
      'Cashi' => 'method_cashi',
      'Bank Transfer' => 'method_bank_transfer',
      'Hawala' => 'method_hawala',
      _ => 'method_cash',
    };
    return get(key, lang);
  }

  static const Map<String, Map<String, String>> _s = {
    'ar': {
      'app_title': 'نظام الفوترة',
      // Login
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'مرحبًا بك في نظام الفوترة',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'login_btn': 'دخول',
      'login_error': 'البريد أو كلمة المرور غير صحيحة',
      'login_error_empty': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
      // Navigation
      'nav_home': 'الرئيسية',
      'nav_customers': 'العملاء',
      'nav_products': 'المنتجات / الخدمات',
      'nav_invoices': 'الفواتير',
      'nav_reports': 'التقارير',
      'nav_chatbot': 'المساعد الذكي',
      'nav_settings': 'الإعدادات',
      'nav_administration': 'المستخدمون وسجل التدقيق',
      'administration_title': 'الإدارة',
      'nav_logout': 'تسجيل الخروج',
      // Dashboard
      'home_title': 'لوحة التحكم',
      'today_revenue': 'إيرادات اليوم',
      'unpaid_count': 'فواتير غير مدفوعة',
      'total_receivables': 'إجمالي المستحقات',
      'customers_count': 'عدد العملاء',
      'invoices_count': 'إجمالي الفواتير',
      'quick_actions': 'إجراءات سريعة',
      'new_invoice': 'فاتورة جديدة',
      'add_customer': 'إضافة عميل',
      'add_product': 'إضافة منتج',
      'sync_status': 'حالة المزامنة',
      'not_synced_yet': 'لم تتم المزامنة بعد',
      'last_synced': 'آخر مزامنة',
      'sync_not_configured': 'المزامنة غير مُفعَّلة',
      // Customers
      'customers_title': 'العملاء',
      'customer_name': 'اسم العميل',
      'customer_phone': 'رقم الهاتف',
      'customer_address': 'العنوان',
      'customer_balance': 'الرصيد المستحق',
      'add_customer_title': 'إضافة عميل جديد',
      'edit_customer_title': 'تعديل بيانات العميل',
      'deactivate_customer': 'إلغاء تفعيل العميل',
      'deactivate_confirm': 'هل أنت متأكد من إلغاء تفعيل هذا العميل؟',
      'no_customers': 'لا يوجد عملاء بعد',
      'search_customers': 'بحث في العملاء...',
      'customer_saved': 'تم حفظ بيانات العميل',
      'customer_deactivated': 'تم إلغاء تفعيل العميل',
      // Products
      'products_title': 'المنتجات / الخدمات',
      'product_name': 'اسم المنتج',
      'product_category': 'الفئة',
      'product_price': 'السعر (جنيه سوداني)',
      'product_unit': 'الوحدة',
      'add_product_title': 'إضافة منتج جديد',
      'edit_product_title': 'تعديل بيانات المنتج',
      'deactivate_product': 'إلغاء تفعيل المنتج',
      'no_products': 'لا توجد منتجات بعد',
      'search_products': 'بحث في المنتجات...',
      'product_saved': 'تم حفظ المنتج',
      'product_deactivated': 'تم إلغاء تفعيل المنتج',
      // Invoices
      'invoices_title': 'الفواتير',
      'create_invoice': 'إنشاء فاتورة',
      'invoice_number': 'رقم الفاتورة',
      'select_customer': 'اختر العميل',
      'add_item': 'إضافة بند',
      'item_description': 'وصف البند',
      'quantity': 'الكمية',
      'unit_price': 'السعر',
      'subtotal': 'المجموع الجزئي',
      'total': 'الإجمالي',
      'tax_vat': 'ضريبة القيمة المضافة 17%',
      'invoice_notes': 'ملاحظات',
      'save_draft': 'حفظ كمسودة',
      'confirm_invoice': 'تأكيد الفاتورة',
      'void_invoice': 'إلغاء الفاتورة',
      'close_invoice': 'إغلاق الفاتورة',
      'record_payment': 'تسجيل دفعة',
      'generate_pdf': 'إنشاء PDF',
      'share_invoice': 'مشاركة الفاتورة',
      'no_items': 'لم يتم إضافة بنود بعد',
      'no_invoices': 'لا توجد فواتير بعد',
      'search_invoices': 'بحث في الفواتير...',
      'invoice_saved': 'تم حفظ الفاتورة',
      'invoice_confirmed': 'تم تأكيد الفاتورة',
      'invoice_voided': 'تم إلغاء الفاتورة',
      'payment_saved': 'تم تسجيل الدفعة',
      'payment_history': 'سجل المدفوعات',
      'no_payments': 'لا توجد مدفوعات بعد',
      'items': 'البنود',
      'select_product': 'اختر منتجاً',
      'no_customer_selected': 'يرجى اختيار العميل',
      'no_items_error': 'يرجى إضافة بند واحد على الأقل',
      // Statuses
      'status_draft': 'مسودة',
      'status_confirmed': 'مؤكدة',
      'status_paid': 'مدفوعة',
      'status_voided': 'ملغاة',
      'status_closed': 'مغلقة',
      // PDF invoice labels
      'pdf_invoice': 'فاتورة',
      'pdf_tax_invoice': 'فاتورة ضريبية',
      'pdf_tax_id': 'الرقم الضريبي',
      'pdf_commercial_registration': 'السجل التجاري',
      'pdf_bill_to': 'فاتورة إلى',
      'pdf_phone': 'الهاتف',
      'pdf_address': 'العنوان',
      'pdf_description': 'الوصف',
      'pdf_qty': 'الكمية',
      'pdf_unit_price': 'سعر الوحدة',
      'pdf_total': 'الإجمالي',
      'pdf_subtotal': 'المجموع الفرعي',
      'pdf_vat': 'ضريبة القيمة المضافة',
      'pdf_grand_total': 'الإجمالي الكلي',
      'pdf_paid': 'المدفوع',
      'pdf_remaining': 'المتبقي',
      'pdf_payment_history': 'سجل الدفعات',
      'pdf_method': 'طريقة الدفع',
      'pdf_date': 'التاريخ',
      'pdf_amount': 'المبلغ',
      'pdf_notes': 'ملاحظات',
      'pdf_thanks': 'شكراً لتعاملكم معنا',
      'pdf_generated_at': 'تم الإنشاء في',
      'offline_banner': 'غير متصل بالإنترنت — البيانات تُحفظ محلياً',
      'demo_mode_badge': 'وضع تجريبي — بيانات محاكاة',
      'chatbot_rule_based': 'مساعد قواعد محلي',
      'payment_reference': 'رقم العملية / المرجع (اختياري)',
      'pdf_reference': 'المرجع',
      'sudapass_btn': 'الدخول عبر سوداباس — قريباً',
      'sudapass_title': 'سوداباس — الهوية الرقمية الوطنية',
      'sudapass_info':
          'سوداباس هو منصة الهوية الرقمية الوطنية السودانية التابعة لهيئة تنظيم الاتصالات والبريد. سيتم تفعيل تسجيل الدخول عبر سوداباس عند إتاحة واجهة برمجية عامة للمطورين. حالياً يرجى استخدام حساب النظام المحلي.',
      'ok': 'حسناً',
      // Payments
      'payment_title': 'تسجيل دفعة',
      'amount_paid': 'المبلغ المدفوع',
      'payment_method': 'طريقة الدفع',
      'payment_notes': 'ملاحظات الدفع',
      'payment_date': 'تاريخ الدفع',
      'remaining_balance': 'المتبقي',
      'total_paid': 'المدفوع',
      // Payment methods
      'method_cash': 'نقداً',
      'method_bankak': 'بنكك',
      'method_bede': 'بيدي',
      'method_cashi': 'كاشي',
      'method_bank_transfer': 'تحويل بنكي',
      'method_hawala': 'حوالة',
      // Reports
      'reports_title': 'التقارير',
      'daily_report': 'التقرير اليومي',
      'monthly_report': 'التقرير الشهري',
      'unpaid_report': 'الفواتير غير المدفوعة',
      'aging_report': 'تقرير التأخير',
      'by_method_report': 'حسب طريقة الدفع',
      'top_products_report': 'أكثر المنتجات مبيعًا',
      'admin_only': 'هذا القسم للمدير فقط',
      'summary': 'ملخص عام',
      'total_revenue': 'إجمالي الإيرادات',
      'this_week': 'هذا الأسبوع',
      'this_month': 'هذا الشهر',
      'revenue_summary': 'ملخص الإيرادات',
      'invoice_status_breakdown': 'توزيع حالة الفواتير',
      'payment_methods_summary': 'طرق الدفع',
      'top_customers': 'أفضل العملاء',
      'top_products': 'أكثر المنتجات',
      'qty_sold': 'الكمية',
      'sales_amount': 'المبيعات',
      'no_report_data': 'لا توجد بيانات',
      'refresh': 'تحديث',
      'products_count': 'عدد المنتجات',
      'paid_invoices': 'الفواتير المدفوعة',
      'confirmed_invoices': 'الفواتير المؤكدة',
      // Chatbot
      'chatbot_title': 'المساعد الذكي',
      'chatbot_hint': 'اسألني عن الفواتير والعملاء...',
      'smart_mode': 'وضع الذكاء الاصطناعي — متصل',
      'offline_mode': 'غير متصل',
      'chatbot_admin_only': 'هذا الطلب متاح للمدير فقط',
      'send': 'إرسال',
      'suggested_questions': 'أسئلة مقترحة',
      // Settings
      'settings_title': 'الإعدادات',
      'language': 'اللغة',
      'language_ar': 'العربية',
      'language_en': 'الإنجليزية',
      'store_name': 'اسم المتجر',
      'vat_toggle': 'تفعيل ضريبة القيمة المضافة 17%',
      'sync_now': 'مزامنة الآن',
      'supabase_url': 'رابط Supabase',
      'supabase_key': 'مفتاح Supabase',
      'cloud_sync': 'المزامنة السحابية',
      'no_internet': 'لا يوجد اتصال بالإنترنت. حاول مجدداً لاحقاً.',
      'sync_success': 'تمت المزامنة بنجاح',
      'sync_failed': 'فشلت المزامنة',
      'pending_sync': 'في انتظار المزامنة',
      'offline_mode_note': 'المزامنة اختيارية. يعمل التطبيق بدون إنترنت.',
      'settings_saved': 'تم الحفظ',
      'syncing': 'جارٍ المزامنة...',
      'store_settings': 'إعدادات المتجر',
      'vat_applies_note': 'تطبق على الفواتير الجديدة فقط',
      'account_section': 'الحساب',
      'current_role_label': 'صلاحيات المستخدم الحالية',
      'sync_up_to_date': 'كل شيء محدّث',
      'sync_partial': 'مزامنة جزئية',
      'user_management': 'إدارة المستخدمين',
      // Common
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'edit': 'تعديل',
      'delete': 'حذف',
      'add': 'إضافة',
      'update': 'تحديث',
      'search': 'بحث...',
      'confirm': 'تأكيد',
      'close': 'إغلاق',
      'back': 'رجوع',
      'yes': 'نعم',
      'no': 'لا',
      'loading': 'جارٍ التحميل...',
      'error': 'حدث خطأ',
      'success': 'تم بنجاح',
      'required_field': 'هذا الحقل مطلوب',
      'invalid_number': 'أدخل رقمًا صحيحًا',
      'admin_role': 'مدير',
      'cashier_role': 'كاشير',
      'currency': 'جنيه',
      'inactive': 'غير نشط',
      'show_inactive': 'إظهار غير النشطين',
      'admin_only_action': 'هذا الإجراء للمدير فقط',
      'void_confirm': 'هل أنت متأكد من إلغاء هذه الفاتورة؟',
      'cannot_void_with_payments': 'لا يمكن إلغاء فاتورة لها مدفوعات مسجلة',
      'amount_exceeds_remaining': 'المبلغ يتجاوز الرصيد المتبقي',
      'pdf_error': 'حدث خطأ أثناء إنشاء الملف',
      'share_error': 'حدث خطأ أثناء المشاركة',
      'pdf_created': 'تم إنشاء الملف بنجاح',
      'invoice_pdf': 'فاتورة',
      'paid': 'مدفوع',
      'remaining': 'متبقي',
      'thank_you': 'شكراً لتعاملكم معنا',
      'generated_at': 'تاريخ الإصدار',
      'logout_confirm': 'هل تريد تسجيل الخروج؟',
      // WhatsApp / SMS / QR
      'notify_customer': 'إشعار العميل',
      'notify_whatsapp': 'واتساب',
      'notify_sms': 'رسالة SMS',
      'view_qr': 'رمز QR للفاتورة',
      'scan_qr_hint': 'امسح الرمز للاطلاع على تفاصيل الفاتورة',
      'whatsapp_not_found': 'تطبيق واتساب غير موجود على هذا الجهاز',
      'sms_not_available': 'الرسائل القصيرة غير متاحة على هذا الجهاز',
      // Utility bills — a real ledger of bills the shop paid on a customer's
      // behalf (no Sudanese provider exposes a public API to check/pay live).
      'nav_utility_bills': 'فواتير الخدمات',
      'utility_bills_title': 'دفعات فواتير الخدمات',
      'utility_electricity': 'الكهرباء',
      'utility_water': 'المياه',
      'utility_telecom': 'اتصالات',
      'utility_explainer':
          'سجّل هنا فواتير الكهرباء والمياه والاتصالات التي تدفعها للعميل نيابة عنه (نقداً أو عبر تطبيقك المصرفي)، مع إيصال قابل للطباعة والمشاركة عبر واتساب.',
      'utility_record_payment': 'تسجيل دفعة فاتورة',
      'account_number': 'رقم العداد / الحساب / الهاتف',
      'service_provider': 'مزود الخدمة',
      'utility_payer_name': 'اسم العميل (اختياري)',
      'utility_payer_phone': 'رقم هاتف العميل (اختياري)',
      'utility_bill_amount': 'مبلغ الفاتورة',
      'utility_service_fee': 'رسوم الخدمة (اختياري)',
      'utility_total_collected': 'الإجمالي من العميل',
      'utility_history': 'سجل المدفوعات',
      'utility_no_history': 'لا توجد مدفوعات مسجلة بعد',
      'utility_service_revenue': 'إيرادات خدمة الفواتير',
      'utility_receipt': 'إيصال',
      'utility_receipt_title': 'إيصال دفع فاتورة خدمة',
      'due_date': 'تاريخ الاستحقاق',
      'no_phone_for_notify': 'لا يوجد رقم هاتف للعميل',
      'operation_failed': 'تعذّر إتمام العملية، حاول مرة أخرى',
      'revenue_last_7_days': 'إيرادات آخر ٧ أيام',
      'no_revenue_yet': 'لا توجد إيرادات بعد',
      'invalid_phone': 'رقم هاتف غير صالح (مثال: 0912345678)',
      // Multi-currency
      'invoice_currency': 'العملة',
      // Credit / بالآجل
      'credit_due_date': 'تاريخ استحقاق الآجل (اختياري)',
      'select_due_date': 'اختر تاريخ الاستحقاق',
      'no_due_date': 'بدون تاريخ استحقاق',
      'clear_due_date': 'إزالة التاريخ',
      'status_overdue': 'متأخرة',
      'credit_limit': 'حد الائتمان',
      'over_credit_limit': 'تجاوز حد الائتمان',
      // Cash drawer
      'nav_cash_drawer': 'صندوق النقدية',
      'cash_drawer_title': 'تسوية صندوق النقدية',
      'open_drawer': 'فتح الصندوق',
      'opening_balance': 'الرصيد الافتتاحي',
      'drawer_open_status': 'الصندوق مفتوح',
      'opened_at': 'وقت الفتح',
      'cash_collected': 'النقد المُحصّل',
      'expected_cash': 'النقد المتوقع',
      'counted_cash': 'النقد المعدود',
      'variance': 'الفرق',
      'close_drawer': 'إغلاق الصندوق',
      'drawer_closed_msg': 'تم إغلاق الصندوق',
      'drawer_already_open': 'يوجد صندوق مفتوح بالفعل',
      'recent_sessions': 'الجلسات الأخيرة',
      'no_drawer_sessions': 'لا توجد جلسات صندوق بعد',
      'variance_over': 'زيادة',
      'variance_short': 'عجز',
      'variance_balanced': 'متوازن',
    },
    'en': {
      'app_title': 'Retail Billing System',
      // Login
      'login_title': 'Sign In',
      'login_subtitle': 'Welcome to Retail Billing System',
      'email': 'Email',
      'password': 'Password',
      'login_btn': 'Sign In',
      'login_error': 'Invalid email or password',
      'login_error_empty': 'Please enter email and password',
      // Navigation
      'nav_home': 'Dashboard',
      'nav_customers': 'Customers',
      'nav_products': 'Products / Services',
      'nav_invoices': 'Invoices',
      'nav_reports': 'Reports',
      'nav_chatbot': 'Smart Assistant',
      'nav_settings': 'Settings',
      'nav_administration': 'Users & Audit Log',
      'administration_title': 'Administration',
      'nav_logout': 'Logout',
      // Dashboard
      'home_title': 'Dashboard',
      'today_revenue': "Today's Revenue",
      'unpaid_count': 'Unpaid Invoices',
      'total_receivables': 'Total Receivables',
      'customers_count': 'Customers',
      'invoices_count': 'Total Invoices',
      'quick_actions': 'Quick Actions',
      'new_invoice': 'New Invoice',
      'add_customer': 'Add Customer',
      'add_product': 'Add Product',
      'sync_status': 'Sync Status',
      'not_synced_yet': 'Not synced yet',
      'last_synced': 'Last synced',
      'sync_not_configured': 'Sync not configured',
      // Customers
      'customers_title': 'Customers',
      'customer_name': 'Customer Name',
      'customer_phone': 'Phone Number',
      'customer_address': 'Address',
      'customer_balance': 'Balance Due',
      'add_customer_title': 'Add New Customer',
      'edit_customer_title': 'Edit Customer',
      'deactivate_customer': 'Deactivate Customer',
      'deactivate_confirm':
          'Are you sure you want to deactivate this customer?',
      'no_customers': 'No customers yet',
      'search_customers': 'Search customers...',
      'customer_saved': 'Customer saved',
      'customer_deactivated': 'Customer deactivated',
      // Products
      'products_title': 'Products / Services',
      'product_name': 'Product Name',
      'product_category': 'Category',
      'product_price': 'Price (SDG)',
      'product_unit': 'Unit',
      'add_product_title': 'Add New Product',
      'edit_product_title': 'Edit Product',
      'deactivate_product': 'Deactivate Product',
      'no_products': 'No products yet',
      'search_products': 'Search products...',
      'product_saved': 'Product saved',
      'product_deactivated': 'Product deactivated',
      // Invoices
      'invoices_title': 'Invoices',
      'create_invoice': 'Create Invoice',
      'invoice_number': 'Invoice #',
      'select_customer': 'Select Customer',
      'add_item': 'Add Item',
      'item_description': 'Item Description',
      'quantity': 'Quantity',
      'unit_price': 'Unit Price',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'tax_vat': 'VAT 17%',
      'invoice_notes': 'Notes',
      'save_draft': 'Save as Draft',
      'confirm_invoice': 'Confirm Invoice',
      'void_invoice': 'Void Invoice',
      'close_invoice': 'Close Invoice',
      'record_payment': 'Record Payment',
      'generate_pdf': 'Generate PDF',
      'share_invoice': 'Share Invoice',
      'no_items': 'No items added yet',
      'no_invoices': 'No invoices yet',
      'search_invoices': 'Search invoices...',
      'invoice_saved': 'Invoice saved',
      'invoice_confirmed': 'Invoice confirmed',
      'invoice_voided': 'Invoice voided',
      'payment_saved': 'Payment recorded',
      'payment_history': 'Payment History',
      'no_payments': 'No payments yet',
      'items': 'Items',
      'select_product': 'Select Product',
      'no_customer_selected': 'Please select a customer',
      'no_items_error': 'Please add at least one item',
      // Statuses
      'status_draft': 'Draft',
      'status_confirmed': 'Confirmed',
      'status_paid': 'Paid',
      'status_voided': 'Voided',
      'status_closed': 'Closed',
      // PDF invoice labels
      'pdf_invoice': 'INVOICE',
      'pdf_tax_invoice': 'TAX INVOICE',
      'pdf_tax_id': 'Tax ID',
      'pdf_commercial_registration': 'Commercial Registration',
      'pdf_bill_to': 'BILL TO',
      'pdf_phone': 'Phone',
      'pdf_address': 'Address',
      'pdf_description': 'Description',
      'pdf_qty': 'Qty',
      'pdf_unit_price': 'Unit Price',
      'pdf_total': 'Total',
      'pdf_subtotal': 'Subtotal',
      'pdf_vat': 'VAT',
      'pdf_grand_total': 'Grand Total',
      'pdf_paid': 'Paid',
      'pdf_remaining': 'Remaining',
      'pdf_payment_history': 'PAYMENT HISTORY',
      'pdf_method': 'Method',
      'pdf_date': 'Date',
      'pdf_amount': 'Amount',
      'pdf_notes': 'NOTES',
      'pdf_thanks': 'Thank you for your business',
      'pdf_generated_at': 'Generated at',
      'offline_banner': 'Offline — data is saved locally',
      'demo_mode_badge': 'Demo mode — simulated data',
      'chatbot_rule_based': 'Rule-based assistant',
      'payment_reference': 'Transaction reference (optional)',
      'pdf_reference': 'Reference',
      'sudapass_btn': 'Sign in with SudaPass — coming soon',
      'sudapass_title': 'SudaPass — National Digital Identity',
      'sudapass_info':
          'SudaPass is Sudan\'s national digital identity platform operated under the TPRA. SudaPass sign-in will be enabled once a public developer API becomes available. For now, please use your local system account.',
      'ok': 'OK',
      // Payments
      'payment_title': 'Record Payment',
      'amount_paid': 'Amount Paid',
      'payment_method': 'Payment Method',
      'payment_notes': 'Payment Notes',
      'payment_date': 'Payment Date',
      'remaining_balance': 'Remaining',
      'total_paid': 'Total Paid',
      // Payment methods
      'method_cash': 'Cash',
      'method_bankak': 'Bankak',
      'method_bede': 'Bede',
      'method_cashi': 'Cashi',
      'method_bank_transfer': 'Bank Transfer',
      'method_hawala': 'Hawala',
      // Reports
      'reports_title': 'Reports',
      'daily_report': 'Daily Report',
      'monthly_report': 'Monthly Report',
      'unpaid_report': 'Unpaid Invoices',
      'aging_report': 'Aging Report',
      'by_method_report': 'By Payment Method',
      'top_products_report': 'Top Products',
      'admin_only': 'This section is for Admin only',
      'summary': 'Overview',
      'total_revenue': 'Total Revenue',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'revenue_summary': 'Revenue Summary',
      'invoice_status_breakdown': 'Invoice Status',
      'payment_methods_summary': 'Payment Methods',
      'top_customers': 'Top Customers',
      'top_products': 'Top Products',
      'qty_sold': 'Qty',
      'sales_amount': 'Sales',
      'no_report_data': 'No data available',
      'refresh': 'Refresh',
      'products_count': 'Products',
      'paid_invoices': 'Paid Invoices',
      'confirmed_invoices': 'Confirmed Invoices',
      // Chatbot
      'chatbot_title': 'Smart Assistant',
      'chatbot_hint': 'Ask about invoices, customers...',
      'smart_mode': 'AI Mode — Online',
      'offline_mode': 'Offline',
      'chatbot_admin_only': 'This query is for Admin only',
      'send': 'Send',
      'suggested_questions': 'Suggested Questions',
      // Settings
      'settings_title': 'Settings',
      'language': 'Language',
      'language_ar': 'Arabic',
      'language_en': 'English',
      'store_name': 'Store Name',
      'vat_toggle': 'Enable VAT 17%',
      'sync_now': 'Sync Now',
      'supabase_url': 'Supabase URL',
      'supabase_key': 'Supabase Anon Key',
      'cloud_sync': 'Cloud Sync',
      'no_internet': 'No internet connection. Try again later.',
      'sync_success': 'Sync completed successfully',
      'sync_failed': 'Sync failed',
      'pending_sync': 'Pending sync',
      'offline_mode_note':
          'Sync is optional. The app works offline without cloud configuration.',
      'settings_saved': 'Saved',
      'syncing': 'Syncing...',
      'store_settings': 'Store Settings',
      'vat_applies_note': 'Applies to new invoices only',
      'account_section': 'Account',
      'current_role_label': 'Current user permissions',
      'sync_up_to_date': 'Everything is up to date',
      'sync_partial': 'Partial sync',
      'user_management': 'User Management',
      // Common
      'save': 'Save',
      'cancel': 'Cancel',
      'edit': 'Edit',
      'delete': 'Delete',
      'add': 'Add',
      'update': 'Update',
      'search': 'Search...',
      'confirm': 'Confirm',
      'close': 'Close',
      'back': 'Back',
      'yes': 'Yes',
      'no': 'No',
      'loading': 'Loading...',
      'error': 'An error occurred',
      'success': 'Saved successfully',
      'required_field': 'This field is required',
      'invalid_number': 'Enter a valid number',
      'admin_role': 'Admin',
      'cashier_role': 'Cashier',
      'currency': 'SDG',
      'inactive': 'Inactive',
      'show_inactive': 'Show Inactive',
      'admin_only_action': 'This action is for Admin only',
      'void_confirm': 'Are you sure you want to void this invoice?',
      'cannot_void_with_payments':
          'Cannot void an invoice with recorded payments',
      'amount_exceeds_remaining': 'Amount exceeds remaining balance',
      'pdf_error': 'Error creating PDF',
      'share_error': 'Error sharing invoice',
      'pdf_created': 'PDF created successfully',
      'invoice_pdf': 'Invoice',
      'paid': 'Paid',
      'remaining': 'Remaining',
      'thank_you': 'Thank you for your business',
      'generated_at': 'Generated at',
      'logout_confirm': 'Are you sure you want to logout?',
      // WhatsApp / SMS / QR
      'notify_customer': 'Notify Customer',
      'notify_whatsapp': 'WhatsApp',
      'notify_sms': 'SMS',
      'view_qr': 'Invoice QR Code',
      'scan_qr_hint': 'Scan to view invoice details',
      'whatsapp_not_found': 'WhatsApp not found on this device',
      'sms_not_available': 'SMS not available on this device',
      // Utility bills — a real ledger of bills the shop paid on a customer's
      // behalf (no Sudanese provider exposes a public API to check/pay live).
      'nav_utility_bills': 'Utility Bills',
      'utility_bills_title': 'Utility Bill Payments',
      'utility_electricity': 'Electricity',
      'utility_water': 'Water',
      'utility_telecom': 'Telecom',
      'utility_explainer':
          'Record electricity, water, and telecom bills you pay on a customer\'s behalf (in cash or via your own banking app), with a printable receipt you can share on WhatsApp.',
      'utility_record_payment': 'Record Bill Payment',
      'account_number': 'Meter / Account / Phone No.',
      'service_provider': 'Provider',
      'utility_payer_name': 'Customer Name (optional)',
      'utility_payer_phone': 'Customer Phone (optional)',
      'utility_bill_amount': 'Bill Amount',
      'utility_service_fee': 'Service Fee (optional)',
      'utility_total_collected': 'Total Collected from Customer',
      'utility_history': 'Payment History',
      'utility_no_history': 'No utility payments recorded yet',
      'utility_service_revenue': 'Utility Service Revenue',
      'utility_receipt': 'Receipt',
      'utility_receipt_title': 'Utility Bill Receipt',
      'due_date': 'Due Date',
      'no_phone_for_notify': 'Customer has no phone number',
      'operation_failed': 'Operation failed, please try again',
      'revenue_last_7_days': 'Revenue — last 7 days',
      'no_revenue_yet': 'No revenue yet',
      'invalid_phone': 'Invalid phone number (e.g. 0912345678)',
      // Multi-currency
      'invoice_currency': 'Currency',
      // Credit / بالآجل
      'credit_due_date': 'Credit due date (optional)',
      'select_due_date': 'Select due date',
      'no_due_date': 'No due date',
      'clear_due_date': 'Clear date',
      'status_overdue': 'Overdue',
      'credit_limit': 'Credit Limit',
      'over_credit_limit': 'Over credit limit',
      // Cash drawer
      'nav_cash_drawer': 'Cash Drawer',
      'cash_drawer_title': 'Cash Drawer Reconciliation',
      'open_drawer': 'Open Drawer',
      'opening_balance': 'Opening Balance',
      'drawer_open_status': 'Drawer Open',
      'opened_at': 'Opened At',
      'cash_collected': 'Cash Collected',
      'expected_cash': 'Expected Cash',
      'counted_cash': 'Counted Cash',
      'variance': 'Variance',
      'close_drawer': 'Close Drawer',
      'drawer_closed_msg': 'Drawer closed',
      'drawer_already_open': 'A drawer is already open',
      'recent_sessions': 'Recent Sessions',
      'no_drawer_sessions': 'No drawer sessions yet',
      'variance_over': 'Over',
      'variance_short': 'Short',
      'variance_balanced': 'Balanced',
    },
  };

  static String get(String key, String lang) {
    return _s[lang]?[key] ?? _s['ar']?[key] ?? key;
  }
}
